### ISSUE TITLE
Bug report: term list shows multiple entries for same term if this term has multiple termmeta values

### ISSUE THREAD

**Issue by danielschwab** [yikesinc/yikes-simple-taxonomy-ordering#1]
I use this plugin (version 0.1) in combination with qtranslate-slug which save the translated slugs for terms in the 'termmeta' table. This produces multiple term entries in the term list of my taxonomy.

I found out that this is because of a bug of this plugin. The inner join in the 'yikes_alter_tax_order' function is selecting all termmeta values instead of filtering just the 'tax_position' value for ordering purposes.

Here my suggested fix for this:
yikes-custom-taxonomy-order.php (line 165):
$pieces['join'] .= " INNER JOIN $wpdb->termmeta AS term_meta ON t.term_id = term_meta.term_id AND term_meta.meta_key = 'tax_position'";

I hope you can include that fix in a new release

**Comment by TheTracyL** [comment]
You can submit a pull request if you like.

**Comment by EvanHerman** [comment]
Hey @danielschwab,

I've gone ahead and merged in your PR, and pushed out a patch to the WordPress.org repository. Version 1.0, which was released today has your patch included and should now have things resolved.

Thanks for the pull request!

Evan

**Comment by danielschwab** [comment]
Hey Evan,
thanks for the info.

Regards, Daniel
