### ISSUE TITLE
Undefined notice when object_type is not defined

### ISSUE THREAD

**Issue by mersadk** [yikesinc/yikes-simple-taxonomy-ordering#10]
On one WP installation I had a strange error, that object_type for taxonomy was not defined and I would get PHP Notices when trying to enable taxonomy sorting.

To fix it I added additional checks in file options.php line 140
```$post_type = ( $tax_object and $tax_object->object_type and sizeof( $tax_object->object_type ) ) ? $tax_object->object_type[0] : 'post'; // setup post type```

Can you update repository and publish new version of plugin?

**Comment by kpu23** [comment]
Hi @mersadk,

Looks good. We will push an update.

Cheers,
Kevin.

**Comment by kpu23** [comment]
1.2.7 is released.

**Comment by mersadk** [comment]
@kpu23 Works now, thanks.
