### ISSUE TITLE
Taxonomy ordering not working on AJAX based queries

### ISSUE THREAD

**Issue by indrek-k** [yikesinc/yikes-simple-taxonomy-ordering#12]
Hi there!

I'm using this plugin on a site which in some occasions also needs to load taxonomies on an ajax request. However:
https://github.com/yikesinc/yikes-inc-simple-taxonomy-ordering/blob/master/yikes-custom-taxonomy-order.php#L114 uses is_admin(), which unfortunately returns true on front-end ajax requests as well (see https://facetwp.com/is_admin-and-ajax-in-wordpress/)

I could fix this by manually adding the filter in my code, but unfortunately there's no way to reference the only instance of Yikes_Custom_Taxonomy_Order as it's initialized but doesn't exist in the global namespace.

Would it be possible to either (a) have the plugin also work on AJAX requests (although I'm not sure how to exclude admin-based ajax requests in that case) or (b) have a way to reference the class instance, for example make it a Singleton?

Thanks!

**Comment by kpu23** [comment]
Hey @indrek-k,

The main plugin class should definitely be set up as a Singleton or at least in a variable that occupies the global namespace. We'll make sure to fix that.

However, to order the taxonomies in an AJAX call, you should be able to use the following parameters in your WP Term Query:
`'meta_key' => 'tax_position'` and `'orderby' => 'tax_position'`

Will that work for you?

Cheers,
Kevin.

**Comment by indrek-k** [comment]
Ah, perfect, totally forgot that option. Thanks!
