### ISSUE TITLE
Error on line 68 after updating to 2.0.0

### ISSUE THREAD

**Issue by leeecoon** [yikesinc/yikes-simple-taxonomy-ordering#15]
Hi,
Noticing an issue after updating Wordpress to 5.1.1 and this Plugin to 2.0.0:

Parse error: syntax error, unexpected 'include' (T_INCLUDE), expecting identifier (T_STRING) in /home/angelu6/public_html/wp-content/plugins/simple-taxonomy-ordering/yikes-custom-taxonomy-order.php on line 68

Looks like the issue is here:

	 * Include our files.
		 */
		private function include() {
			include(YIKES_STO_PATH . 'lib/options.php');
		}

Thank you in advance :)

**Comment by kpu23** [comment]
Hi @leeecoon,

First. thanks for reporting this and apologies for the issue.

I believe this is a problem with older PHP versions. The plugin was tested with PHP version >= 7.0.0. After doing some research, it looks like there is an issue with calling a class method `include` on PHP versions < 7.

This is an easy fix on our end but I'd rather wait a while to see if any other issues come up before releasing it.

In the meantime, do you need help changing the plugin's code to get it working on your site?

Let me know.

Thank you,
Kevin.

**Comment by leeecoon** [comment]
Hi @kpu23,
Thank you so much for the quick response. I will try updating to at least version 7.0.0 of PHP (that is the highest version that the hosting company is allowing for now). I'll see if that works for me and if not I will let you know.
Thanks again!
Lena
