### ISSUE TITLE
New query crashes get_terms

### ISSUE THREAD

**Issue by petertflem** [yikesinc/yikes-simple-taxonomy-ordering#3]
Hello :)

We have a WordPress site which was using your plugin. Suddenly, functionality using get_terms stopped working.

Here is an errors from the log. I've just x-ed out the taxonomy name.

```
2016/07/21 13:20:21 [error] 2037#2037: *302 FastCGI sent in stderr: "PHP message: WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'term_meta.meta_value ASC' at line 1 for query SELECT  t.term_id, t.name, tt.count, tt.taxonomy FROM wp_terms AS t  INNER JOIN w p_term_taxonomy AS tt ON t.term_id = tt.term_id INNER JOIN wp_termmeta AS term_meta ON t.term_id = term_meta.term_id AND term_meta.meta_key = 'tax_position' WHERE tt.taxonomy IN ('xxxxxx') AND tt.count > 0 term_meta.meta_value ASC [...] after this was just a call stack leadning up to get_terms
```

There were a couple more, similar, errors.

We were just doing something like `get_terms('taxonomy', [and some args here]);`.

I deactivated your plugin, and the site started working again.

WordPress version: 4.5.3

**Comment by EvanHerman** [comment]
Hi Peterflem,

Where is this occurring? Is this on the front end of a site? For the taxonomy that this is happening on, is the taxonomy enabled on the simple taxonomy ordering settings page?

I just set up a test instance, and I'm not encountering the issue on my end.

Thanks,
Evan

**Comment by petertflem** [comment]
Yes, it is. Hm, then I'm not sure what's causing it. Any debuginfo I could give you?

**Comment by EvanHerman** [comment]
We just pushed out version 1.1 which reverts back to the original query, with the ORDER BY arguemnt. I believe that was the issue.

Give things an update shot and let me know if things are fixed on your end.

Thanks,
Evan

**Comment by doppiogancio** [comment]
Hi,

I am using version 1.2.3 and I noticed that when the plugin is enabled the wp function "get_the_term_list" returns always an empty result.

**Comment by doppiogancio** [comment]
I have also discovered the reason. The plugin does not make any difference when builds the term query, so, it expects the term meta with key 'tax_position' always available, but this term meta key is not present if that particular taxonomy has never been sorted.

I recommend building the query in that custom way only if that taxonomy have been sorted at least one, if not, just leave the default behavior.

Thanks in advance
Fabrizio

**Comment by kpu23** [comment]
Hello Fabrizio,

I'll get on that. Thanks for letting us know.

Cheers,
Kevin.

**Comment by kpu23** [comment]
Hello again Fabrizio,

Using a taxonomy named 'breed' that has never been sorted (has no tax_position items in the termmeta table), with a term attached to post ID 70 (  `get_the_term_list( 70, 'breed' )` ) is returning the expected results for me. 

What am I doing wrong here?

**Comment by doppiogancio** [comment]
Is the plugin enabled? If yes, it has to return an empty result since it won't be able to join the tables.
If the list is returned to you it only means that either the plugin is disabled or that it is not executing that query filter.

**Comment by doppiogancio** [comment]
Considering that

1. Every term is stored in "**wp_terms**" table
2. And if this plugin is enabled the ordering of the terms is stored in "**wp_termmeta**" table
3. If you don't do any edit/save on already existing taxonomies the "**wp_termmeta**" should be empty

What happens if you join the table "**wp_terms**" with an empty "**wp_termmeta**"?

`/*
		*	Re-Order the taxonomies based on the tax_position value
		*	@since 0.1
		*/
		public function yikes_alter_tax_order( $pieces, $taxonomies, $args ) {
			foreach( $taxonomies as $taxonomy ) {
				// confirm the tax is set to hierarchical -- else do not allow sorting
				if( $this->yikes_is_taxonomy_position_enabled( $taxonomy ) ) {
					global $wpdb;
					$join_statement = " INNER JOIN $wpdb->termmeta AS term_meta ON t.term_id = term_meta.term_id AND term_meta.meta_key = 'tax_position'";
					if ( ! $this->yikes_does_substring_exist( $pieces['join'], $join_statement ) ) {
						$pieces['join'] .= $join_statement;
					}
					$pieces['orderby'] = "ORDER BY CAST( term_meta.meta_value AS UNSIGNED )";
				}
			}
			return $pieces;
		}`

**Comment by doppiogancio** [comment]
I think that, according to my previous example, even if you a taxonomy with terms the result of get_terms will be empty as reported.

**Comment by doppiogancio** [comment]
my suggestion is to check if the **termmeta** are populated each time the plugin gets activated

**Comment by kpu23** [comment]
@doppiogancio,

Understood. Perhaps we should just do a `LEFT JOIN`.

**Comment by doppiogancio** [comment]
@kpu23 by "left joining" you will receive a "null" instead of the meta_value (defining the order of that meta).

Just check what happens when casting a "null" to UNSIGNED

Piece of code
`ORDER BY CAST( term_meta.meta_value AS UNSIGNED )`

**Comment by kpu23** [comment]
`LEFT JOIN` is working for me on a site with empty termmeta. MySQL ignores(?) the `ORDER BY CAST( NULL AS UNSIGNED )`.
