### ISSUE TITLE
Not working from an AJAX call (with user taxonomy)

### ISSUE THREAD

**Issue by certainlyakey** [yikesinc/yikes-simple-taxonomy-ordering#4]
Hi! Thanks for a great plugin with a smooth and non-intrusive UI.

Not sure what exactly has caused this, but automatic sorting of terms didn't work for me if a function containing `get_terms` is executed from an AJAX call. The taxonomy was manually registered for users.

So the same code (same function was used for an AJAX call and usual template loading) returned terms sorted in a default order (alphabetically by term name) if it was executed via AJAX and correctly sorted by YIKES if it was executed on template load (normally):

```php
$user_positions = get_terms( 'position', array(
    'hide_empty' => false,
    'fields' => 'ids'
    )
);
```

I changed the code to this and sorting started to work in both cases:

```php
$user_positions = get_terms( 'position', array(
    'hide_empty' => false,
    'fields' => 'ids',
    'meta_key' => 'tax_position',
    'orderby' => 'tax_position'
    )
);
```

**Comment by kpu23** [comment]
Hi @certainlyakey,

Just to clarify what you're saying... You're writing your AJAX call grabbing terms, and when you _don't_ add the `tax_position` meta_query, the items are returned alphabetically, but when you add the `tax_position` part to the query, they are returned in the correct (user-sorted) order? 

Cheers,
Kevin.

**Comment by certainlyakey** [comment]
Yes, exactly that. If I don't use AJAX — everything works without `tax_position`.

**Comment by kpu23** [comment]
Hi @certainlyakey,

Yes! I'm glad you figured this out and I hope it didn't take you too much time. This is something we're aware of. 

In fact, I'm not sure why it ever works without specifying the `tax_position` value; I don't think it's AJAX related, but clearly there is an underlying factor that affects AJAX calls and not non-AJAX calls. (Sorry if that was confusing).

I'm adding some documentation to the plugin now. Thanks for letting us know :-).

Cheers,
Kevin.

**Comment by kpu23** [comment]
I added a sentence for clarification on this in the readme.txt. https://wordpress.org/plugins/simple-taxonomy-ordering/other_notes/

**Comment by certainlyakey** [comment]
Thanks! Was glad to help.
