### ISSUE TITLE
Readme — custom post types or custom taxonomies?

### ISSUE THREAD

**Issue by certainlyakey** [yikesinc/yikes-simple-taxonomy-ordering#8]
It's mentioned in the readme files that 

```
#### Custom Post Types
Alternatively, if you've defined a [custom post type](https://codex.wordpress.org/Post_Types) that you'd like to allow drag & drop sorting on, you'll want to pass in a `tax_position` parameter to the `$args` array inside of [register_taxonomy](https://codex.wordpress.org/Function_Reference/register_taxonomy). You can place this line directly after `'hierarchical'`.
```

Did you mean custom taxonomies instead of custom post types? This plugin can't as far as i understand enable sorting of page-like post types, it only works with taxonomies.

**Comment by kpu23** [comment]
Hi @certainlyakey,

Yes you're absolutely correct: we meant custom taxonomies. We will fix that.

Thank you.

All the best,
Kevin.
